### ISSUE TITLE
Нельга ўказаць адзін шрыфт ці не ўказваць увогуле

### ISSUE THREAD

**Issue by belarusaed** [anibel-net/player#1]
Плэер працуе толькі калі ў запыце перадаецца як мінімум два шрыфты. Калі пакінуць толькі адзін, ці не перадаваць увогуле, старонка не рэндарыцца:

```
TypeError: /views/player.pug:7
    5|     meta(name='audiosrc' content=audioSrc)

    6|     meta(name='subsrc' content=subSrc)

  > 7|     for font in fonts

    8|         meta(name='fontsrc' content=font)

    9|     script(defer='defer' src='main.js')

    10| video#video.video-js.vjs-default-skin.vjs-big-play-centered(controls='' data-setup='{"fluid": true}')


Cannot read properties of undefined (reading 'length')
    at eval (eval at wrap (/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:23:32)
    at eval (eval at wrap (/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:38:4)
    at template (eval at wrap (/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:50:7)
    at Object.exports.renderFile (/node_modules/pug/lib/index.js:454:38)
    at Object.exports.renderFile (/node_modules/pug/lib/index.js:444:21)
    at View.exports.__express [as engine] (/node_modules/pug/lib/index.js:493:11)
    at View.render (/node_modules/express/lib/view.js:135:8)
    at tryRender (/node_modules/express/lib/application.js:640:10)
    at Function.render (/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/node_modules/express/lib/response.js:1017:7)
```

**Comment by belarusaed** [comment]
Fixed: bb299afd0ff65e3f7af32e5c8266748279022e6b
